version: '3'

#============================================#
# Docker compose network config
#============================================#
networks:
  ots-redis:

services:

  onetimesecret:
    container_name: ots
    image: 'binbash/onetimesecret'
    restart: always
    ports:
      - '7143:7143'
    volumes:
      - './config:/etc/onetime/config'
      - './redis:/var/run/redis'
    environment:
      - OTS_NAME=user
    depends_on:
      - redis
    links:
      - redis
    networks:
      - ots-redis

  redis:
    command: redis-server --appendonly yes
    container_name: redis
    image: redis:latest
    expose:
      - '7179'
    networks:
      - ots-redis
